plugins: [
  "@semantic-release/commit-analyzer",
  '@semantic-release/release-notes-generator',
  "@semantic-release/github",
  [
    "@semantic-release/exec", {
      "prepareCmd": "cargo set-version ${nextRelease.version}",
      "publishCmd": "cargo publish --token ${process.env.CARGO_API_TOKEN} --allow-dirty"
    },
  ]
]
